In [46]:
import pandas as pd
import pandas as pd
import seaborn as sns
from scipy import stats
import numpy as np
import math
import datetime

df46 = pd.read_excel (r'D:/NO3/2022/OL46_2022.xls', sheet_name='no')
df46 = df46.set_index(['DATE'])
df46 = df46.drop(columns = ['NO', 'SAL','STATION', 'LOCATION', 'SWSG', 'DBT', 'CSQ', 'MEM', 'PWR'])

#create list of date range
start_date = datetime.date(2022,1,1)
list_jan = [(start_date + datetime.timedelta(days=day)).isoformat() for day in range(31)]

#create required variable
my_var = {}
my_z = {}
list_tgl = {}

i = 0
range_date = [i for i in range(1,32)]
for j in range(1,32):
    i +=1 
    my_var['jan_' +str(i)] = df46.loc[f"{list_jan[i-1]}"]
    list_tgl['tgl' +str(i)] = sorted(df46.loc[f"{list_jan[i-1]}"]['NO3'].tolist())

In [2]:
q1 = {}
q3 = {}
q1_support = ["q1_" + str(x) for x in range(1,32)]
q3_support = ["q3_" + str(x) for x in range(1,32)]

i = 1
for key in list_tgl:
    q1['q1_' + str(i)] = np.quantile(list_tgl[key], .25)
    q3['q3_' + str(i)] = np.quantile(list_tgl[key], .75)
    i +=1

In [3]:
min_iqr = {}
max_iqr = {}
for i in range(0, 31):
    min_iqr['min_iqr_' + str(i)] = math.floor(q1[q1_support[i]] - 1.5 * (q3[q3_support[i]] - q1[q1_support[i]]))
    max_iqr['max_iqr_' + str(i)] = math.ceil(q3[q3_support[i]] + 1.5 * (q3[q3_support[i]] - q1[q1_support[i]]))

In [4]:
def outliers(x):
    outlier = []
    #j = 0
    for i in x:
        if (i < min_iqr[f"min_iqr_{out}"]) or (i > max_iqr[f"max_iqr_{out}"]):
            outlier.append(i)
        #j+=1
    return len(outlier)

date_outlier = []
out = 0
for i in list_tgl:
    data = outliers(list_tgl[i])
    date_outlier.append(data)
    out +=1

In [22]:
#date_outlier

In [24]:
date_normal = []
date_fluctuatif = []
dn = 1
df = 1

for i, date in enumerate(date_outlier):
    if date == 0:
        date_normal.append(f"jan_{i+1}")
    else:
        date_fluctuatif.append(f"jan_{i+1}")

In [32]:
print("date where the nitrate measurement seems to be normal : ")
for i in date_normal:
    print(i, end="; ")

date where the nitrate measurement seems to be normal :
jan_1; jan_4; jan_5; jan_6; jan_7; jan_8; jan_9; jan_10; jan_11; jan_12; jan_13; jan_14; jan_15; jan_16; jan_17; jan_18; jan_19; jan_20; jan_21; jan_22; jan_23; jan_24; jan_25; jan_29; jan_31;

In [47]:
my_var['jan_18']

,DT,TIME,pH,DO,COND,TURB,TEMP,TDS,NH4,BOD,TSS,COD,NO3
DATE,,,,,,,,,,,,,
2022-01-18,2022-01-18 00:00:00,00:00:00,7.89,4.50,18.6,111.3,24.3,161.8,0.0,18.52,201.99,78.84,1.82
2022-01-18,2022-01-18 01:00:00,01:00:00,7.92,4.81,18.4,85.4,23.8,160.1,0.0,18.52,163.88,76.33,1.89
2022-01-18,2022-01-18 02:00:00,02:00:00,7.95,4.97,19.0,58.6,23.4,165.3,0.0,18.52,99.88,47.97,1.98
2022-01-18,2022-01-18 03:00:00,03:00:00,7.79,5.04,19.5,42.3,23.2,169.7,0.0,18.52,61.89,36.84,2.08
2022-01-18,2022-01-18 04:00:00,04:00:00,7.76,5.06,20.1,32.1,23.0,174.9,0.0,18.52,39.55,28.84,2.15
2022-01-18,2022-01-18 05:00:00,05:00:00,7.55,4.91,20.5,26.8,22.9,178.4,0.0,18.52,31.97,24.47,2.13
2022-01-18,2022-01-18 06:00:00,06:00:00,7.80,4.56,21.0,21.8,22.8,182.7,0.0,18.52,19.79,20.73,2.17
2022-01-18,2022-01-18 07:00:00,07:00:00,7.86,4.82,21.1,19.4,22.8,183.6,0.0,18.52,11.31,17.13,2.19
2022-01-18,2022-01-18 08:00:00,08:00:00,7.87,4.92,21.3,18.2,22.8,185.3,0.0,18.52,4.06,15.04,2.20
2022-01-18,2022-01-18 09:00:00,09:00:00,7.81,5.63,21.7,64.5,23.0,188.8,0.0,18.52,126.57,48.91,2.31
2022-01-18,2022-01-18 10:00:00,10:00:00,8.18,5.80,21.8,43.3,23.0,189.7,0.0,18.52,62.32,41.18,2.34
2022-01-18,2022-01-18 11:00:00,11:00:00,8.05,5.38,21.9,37.3,23.3,190.5,0.0,18.52,48.75,25.65,2.31
2022-01-18,2022-01-18 12:00:00,12:00:00,8.08,5.50,22.0,41.1,23.9,191.4,0.0,5.58,54.95,24.88,2.34
2022-01-18,2022-01-18 13:00:00,13:00:00,8.10,5.43,22.0,37.3,24.4,191.4,0.0,5.58,42.53,22.02,2.31
2022-01-18,2022-01-18 14:00:00,14:00:00,8.13,5.61,22.0,32.3,24.9,191.4,0.0,5.58,36.72,20.67,2.21
2022-01-18,2022-01-18 15:00:00,15:00:00,7.51,5.05,22.2,26.1,25.2,193.1,0.0,3.64,19.66,16.39,2.15
2022-01-18,2022-01-18 16:00:00,16:00:00,7.88,5.38,22.2,34.2,25.3,193.1,0.0,3.64,40.09,20.87,2.11
2022-01-18,2022-01-18 17:00:00,17:00:00,7.99,5.34,22.4,26.0,25.3,194.9,0.0,3.64,26.47,18.96,2.10
2022-01-18,2022-01-18 18:00:00,18:00:00,8.38,5.44,22.4,22.1,25.2,194.9,0.0,3.64,17.77,15.81,2.08
2022-01-18,2022-01-18 19:00:00,19:00:00,8.56,5.41,22.5,18.0,25.0,195.8,0.0,3.64,7.24,13.48,2.06
2022-01-18,2022-01-18 20:00:00,20:00:00,8.52,5.54,22.6,15.3,24.7,196.6,0.0,3.64,0.00,12.26,2.06
2022-01-18,2022-01-18 21:00:00,21:00:00,8.64,5.59,22.7,15.1,24.5,197.5,0.0,3.64,0.00,11.84,2.09
2022-01-18,2022-01-18 22:00:00,22:00:00,8.79,5.63,22.9,15.7,24.2,199.2,0.0,2.58,0.12,11.64,2.16
2022-01-18,2022-01-18 23:00:00,23:00:00,8.79,5.54,23.0,14.4,24.0,200.1,0.0,2.58,0.00,11.33,2.11

In [36]:
print("date where the nitrate measurement seems to be fluctuatif : ")
for i in date_fluctuatif:
    print(i, end="; ")

date where the nitrate measurement seems to be fluctuatif :
jan_2; jan_3; jan_26; jan_27; jan_28; jan_30;

In [48]:
my_var['jan_30']

,DT,TIME,pH,DO,COND,TURB,TEMP,TDS,NH4,BOD,TSS,COD,NO3
DATE,,,,,,,,,,,,,
2022-01-30,2022-01-30 00:00:00,00:00:00,9.86,5.27,23.5,11.2,24.5,204.5,0.0,2.37,0.00,10.25,81.30
2022-01-30,2022-01-30 01:00:00,01:00:00,9.48,5.33,23.6,10.1,24.2,205.3,0.0,2.37,0.00,9.73,31.80
2022-01-30,2022-01-30 02:00:00,02:00:00,8.71,5.32,23.6,11.4,24.0,205.3,0.0,2.37,0.00,9.67,43.40
2022-01-30,2022-01-30 03:00:00,03:00:00,9.36,5.49,23.7,11.9,23.7,206.2,0.0,2.02,0.00,9.09,63.80
2022-01-30,2022-01-30 04:00:00,04:00:00,10.24,5.57,23.8,10.4,23.4,207.1,0.0,2.02,0.00,8.79,38.90
2022-01-30,2022-01-30 05:00:00,05:00:00,10.35,5.62,23.9,10.1,23.3,207.9,0.0,2.02,0.00,8.35,112.70
2022-01-30,2022-01-30 06:00:00,06:00:00,10.23,5.64,23.8,10.1,23.1,207.1,0.0,2.02,0.00,7.94,81.70
2022-01-30,2022-01-30 07:00:00,07:00:00,10.19,5.59,23.8,11.7,22.9,207.1,0.0,1.74,0.00,7.85,24.50
2022-01-30,2022-01-30 08:00:00,08:00:00,9.65,5.89,23.9,11.4,22.8,207.9,0.0,1.74,0.00,7.68,100.10
2022-01-30,2022-01-30 09:00:00,09:00:00,8.96,5.78,23.9,9.5,22.9,207.9,0.0,1.74,0.00,7.60,10.36
2022-01-30,2022-01-30 10:00:00,10:00:00,9.35,4.66,24.0,9.7,23.3,208.8,0.0,1.74,0.00,7.67,50.70
2022-01-30,2022-01-30 11:00:00,11:00:00,9.22,4.37,23.9,10.1,23.8,207.9,0.0,1.74,0.00,7.83,213.00
2022-01-30,2022-01-30 12:00:00,12:00:00,7.87,4.45,23.7,10.1,24.7,206.2,0.0,1.74,0.00,7.83,18.37
2022-01-30,2022-01-30 13:00:00,13:00:00,8.02,4.38,23.8,10.3,25.5,207.1,0.0,1.74,0.00,9.12,2.04
2022-01-30,2022-01-30 14:00:00,14:00:00,8.02,4.59,23.7,10.7,25.9,206.2,0.0,1.74,0.00,9.10,2.04
2022-01-30,2022-01-30 15:00:00,15:00:00,8.64,5.24,23.7,13.7,25.8,206.2,0.0,2.06,0.00,9.31,5.52
2022-01-30,2022-01-30 16:00:00,16:00:00,9.29,5.20,23.2,14.0,25.3,201.8,0.0,2.06,0.05,11.83,171.20
2022-01-30,2022-01-30 17:00:00,17:00:00,9.53,5.39,22.6,17.1,24.9,196.6,0.0,2.06,4.73,14.01,434.00
2022-01-30,2022-01-30 18:00:00,18:00:00,8.01,5.47,20.0,140.4,24.3,174.0,0.0,15.18,243.05,66.44,35.00
2022-01-30,2022-01-30 19:00:00,19:00:00,9.04,5.28,18.4,190.4,24.0,160.1,0.0,21.07,358.11,91.09,81.70
2022-01-30,2022-01-30 20:00:00,20:00:00,8.65,5.06,17.3,207.0,23.8,150.5,0.0,21.07,421.25,104.66,53.20
2022-01-30,2022-01-30 21:00:00,21:00:00,8.70,4.61,16.8,196.0,23.6,146.2,0.0,21.07,418.28,102.51,34.30
2022-01-30,2022-01-30 22:00:00,22:00:00,8.92,4.95,16.5,184.9,23.4,143.6,0.0,21.07,444.63,102.54,57.80
2022-01-30,2022-01-30 23:00:00,23:00:00,8.65,4.87,17.2,135.9,23.3,149.6,0.0,19.58,333.21,84.85,70.30